name: Tests

on: [push]

jobs:
    install:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3

            - uses: shivammathur/setup-php@v2
              with:
                php-version: 8.1
                coverage: none

            - uses: "ramsey/composer-install@v1"


    tests:
        runs-on: ubuntu-latest
        needs: [install]
        steps:
            - run: composer run tests

    code_analysis:
        runs-on: ubuntu-latest
        needs: [ install ]
        steps:
            - run: ./vendor/bin/phpstan --error-format=github

    generate_documentation:
        runs-on: ubuntu-latest
        needs: [ tests, code_analysis ]
        steps:
            - run: composer run documentation
